### PR TITLE
Improve interoperability with requested attributes

### PR DESCRIPTION
**Pull request by sitya**
We have implemented two addtional options for the module:

* `strict`: if false, it allows to release attributes to entities having no, or unknown entity category, based on requested attributes
* `allowRequestedAttributes`: allow to release additional requested attributes than configured in the list of the configuration of an entity category

Default values are set that these options do not change the default behave of the module. More details and examples are in the README. With these options it is much easier to configure complex rules based on entity categories and requested attributes.

We in eduID.hu use our version of this modul in production without any issue.

### CODE REVIEW

**Comment by bajnokk** [comment]
I just wanted to add that the changes do not change the module behaviour with existing configurations. (Not counting the unlikely case when one calls his entityCategory 'strict' or 'allowRequestedAttributes'.)

Keeping backwards compatibility was the primary reason why _allowRequestedAttributes_ is not defined per-category.

**Comment by bajnokk** [comment]
Just noticed the first commit about the namespaces. I think it's a separate change, with which the module can be made to work with SSP 1.14.x (as I was told, but I don't know how the namespace change is handled in SSP). 

Probably there should be two branches, one for SSP master and one for the released versions, while a revamped (rebased, typo-clean) pull request may be submitted to either of them.

Also the last commit removes the 'soft' line brakes from the README, that is also a tangent (but consequentially large) change.

**Comment by jaimeperez** [comment]
I don't think anybody should be using SSP 1.14 nowadays. There are serious security issues in versions that old.

In any case, the module should use namespaced classes, not the old class names. It's been quite some time since namespaces in modules were supported by SSP (1.15) anyway. So in a way, making the module work for people using old, vulnerable versions of SSP feels like removing the few incentives they might have to upgrade.

**Comment by sitya** [comment]
@jaimeperez Yup, it is true, somehow the commit contained the "namespacing" changes got out from the PR... sorry. But it is definitely compatible with the latest version of SSP, tested before merged.

https://github.com/simplesamlphp/simplesamlphp-module-entitycategories/commit/75514c67963964365b239bc3b47aa7f84081885a

**Comment by jaimeperez** [comment]
Yeah, currently both PSR-0 and PSR-4 class names are supported, so it should work, but still I don't think we should go back to PSR-0.

**Comment by sitya** [comment]
I fully agree about not to go back PSR-0, and sorry for being lama... but it uses PSR-4: https://github.com/simplesamlphp/simplesamlphp-module-entitycategories/blob/master/lib/Auth/Process/EntityCategory.php, or where do you see PSR-0 which I should refactor?

**Comment by jaimeperez** [comment]
Ah, I see, sorry, I missed the merge commit that reverted that change!

**Pull request merged**
